encoding: utf-8

# SEO相关信息
title: 铢钧的字
description: 铢钧的字体部落格
keywords: DWNfonts,diaowinner,LUCUBEO,ChineseDictionaries,font,ttf,otf,bdf,Bitmap,Pixel,BitsNPicas
author: TMaize
footerText: 'Copyright © 2022 diaowinner'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://dwnfonts.github.io'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://itch.io/profile/diaowinner

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 索引
    url: /
  - title: 类别
    url: /pages/categories.html
  - title: 寻找
    url: /pages/search.html
  - title: 连结
    url: /pages/links.html
  - title: itch
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: true

# 友情链接
links:
  - title: 猫啃网
    url: https://www.maoken.com
  - title: zFont找字体
    url: http://zfont.cn